{{- if .Values.global.applications.jenkins.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: {{ .Values.global.argocd.repoURL }}
      targetRevision: {{ .Values.global.argocd.targetRevision }}
      ref: values
    - repoURL: {{ .Values.global.argocd.repoURL }}
      targetRevision: {{ .Values.global.argocd.targetRevision }}
      path: charts/jenkins
      helm:
        valueFiles:
          - $values/values-global.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: cicd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
{{- end }}

# Made with Bob
