{{- if .Values.defaultPolicy.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-opa-policy
  labels:
    app: opa
    release: {{ .Release.Name }}
data:
  {{ .Values.defaultPolicy.name }}.rego: |
{{ .Values.defaultPolicy.content | indent 4 }}
{{- end }}
