{{- if .Values.declarativeConfig.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  labels:
    app: kong
    release: {{ .Release.Name }}
data:
  kong.yml: |
{{ .Values.declarativeConfig.config | indent 4 }}
{{- end }}
